package sdk

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"errors"
	"os"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/sirupsen/logrus"
	v1 "go.alargerobot.dev/gatekeeper/sdk/rpc/endpoint_manager/v1"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
)

type GatekeeperClient struct {
	config          GatekeeperClientConfig
	grpcClient      *grpc.ClientConn
	endpointManager v1.EndpointManagerClient
	epsServer       *endpointServicesServer
	gkCreds         GatekeeperCredentials
	logger          *logrus.Logger
}

type GatekeeperClientConfig struct {
	GatekeeperAPIAddress string
	EndpointServicesPort int
}

type DeviceAuthRequest struct {
	Message   string
	RequestID string
}

type DeviceAuthClientResponse struct {
	Message   string `json:"message"`
	Signature string `json:"signature"`
	RequestID string `json:"requestID"`
}

type GatekeeperCredentials struct {
	Id   string `json:"id"`
	Cert struct {
		CACert      string `json:"ca_cert"`
		Certificate string `json:"certificate"`
		ExpiresAt   string `json:"expiresAt"`
		IssuerCert  string `json:"issuerCert"`
		PrivateKey  string `json:"private_key"`
	} `json:"cert"`
}

// # Description
//
// NewGatekeeperClient initializes the gRPC client reponsible for commuicating with Gatekeeper and
// starts listeners for various Gatekeeper services.
//
// # Usage note
//
// Connection to Gatekeeper currently requires the certificate blob generated by Gatekeeper upon
// service creation, be present in the same directory as the service binary. These credentials
// should be saved completely unmodified, in a in a JSON file named "gatekeeper-credentials.json",
func NewGatekeeperClient(config GatekeeperClientConfig) *GatekeeperClient {
	creds, e := os.ReadFile("gatekeeper-credentials.json")
	if e != nil {
		panic(e)
	}
	var gkCreds GatekeeperCredentials
	e = json.Unmarshal(creds, &gkCreds)
	if e != nil {
		panic(e)
	}

	cert, err := tls.X509KeyPair([]byte(gkCreds.Cert.Certificate), []byte(gkCreds.Cert.PrivateKey))
	if err != nil {
		panic(err)
	}

	ca := x509.NewCertPool()
	caFile := []byte(gkCreds.Cert.CACert)

	ca.AppendCertsFromPEM(caFile)

	grpcClient, e := grpc.NewClient("dns:///"+config.GatekeeperAPIAddress, grpc.WithTransportCredentials(
		credentials.NewTLS(&tls.Config{
			ServerName:   "gatekeeper",
			Certificates: []tls.Certificate{cert},
			RootCAs:      ca,
		})))

	if e != nil {
		panic(e)
	}

	ess := NewEndpointServiceServer(false, "")
	go ess.ListenAndServe(config.EndpointServicesPort)

	gkc := &GatekeeperClient{
		epsServer:       ess,
		config:          config,
		grpcClient:      grpcClient,
		gkCreds:         gkCreds,
		endpointManager: v1.NewEndpointManagerClient(grpcClient),
	}

	gkc.logger = logrus.New()
	gkc.logger.Out = os.Stderr
	gkc.logger.SetLevel(logrus.DebugLevel)

	expTime, err := strconv.Atoi(gkCreds.Cert.ExpiresAt)
	gkc.LogInfo("now", time.Now().UTC().AddDate(0, 0, 5).Unix(), time.Unix(int64(expTime), 0).Format("2006-01-02 15:04:05 MST"))

	if time.Now().UTC().AddDate(0, 0, 5).Unix() == int64(expTime) {
		gkc.LogInfo("", "", "renew credentials...")
	} else if time.Now().UTC().Unix() == int64(expTime) {
		gkc.LogInfo("", "", "renew credentials...")
	} else if time.Now().UTC().Unix() > int64(expTime) {
		gkc.LogInfo("", "", "renew credentials...")
	}

	go gkc.certRenewTimer()

	return gkc
}

// # Description
//
// RegisterGRPCServiceEndpoint registers a gRPC service reachable at "address" with Gatekeeper
//   - address should be formated: <ip-address:port>
//   - tags are optional, specify []string{} if no tags are to applied
func (gc *GatekeeperClient) RegisterGRPCServiceEndpoint(serviceName, grpcServiceName, address string, tags []string) error {
	return gc.registerEPInternal(serviceName, grpcServiceName, address, tags)
}

// # Description
//
// RegisterServiceEndpoint registers a non-gRPC service reachable at "address" with Gatekeeper
//   - address should be formated: <ip-address:port>
//   - tags are optional, specify []string{} if no tags are to applied
func (gc *GatekeeperClient) RegisterServiceEndpoint(serviceName, address string, tags []string) error {
	return gc.registerEPInternal(serviceName, serviceName, address, tags)
}

func (gc *GatekeeperClient) registerEPInternal(serviceName, endpointName, address string, tags []string) error {
	addrParts := strings.Split(address, ":")

	if len(addrParts) != 2 {
		return errors.New("invalid address specified. address format is: <ip-address:port>")
	}

	_, e := gc.endpointManager.RegisterServiceEndpoint(context.Background(), &v1.NewServiceEndpoint{
		Tags:             tags,
		Endpoint:         address,
		ServiceName:      serviceName,
		EndpointName:     endpointName,
		HealthCheckRoute: "https://" + addrParts[0] + ":" + strconv.Itoa(gc.config.EndpointServicesPort) + "/ping",
	})
	return e
}
func (gc *GatekeeperClient) LogInfo(extraKey string, extraValue interface{}, entry interface{}) {
	pc, _, line, _ := runtime.Caller(1)
	funcObj := runtime.FuncForPC(pc)
	runtimeFunc := regexp.MustCompile(`^.*\.(.*)$`)
	name := runtimeFunc.ReplaceAllString(funcObj.Name(), "$1")

	if extraKey != "" {
		gc.logger.WithFields(logrus.Fields{extraKey: extraValue, "func": name, "line": line}).Infoln(entry)
	} else {
		gc.logger.WithFields(logrus.Fields{"func": name, "line": line}).Infoln(entry)
	}
}
func (gc *GatekeeperClient) certRenewTimer() {
	expTime, err := strconv.Atoi(gc.gkCreds.Cert.ExpiresAt)
	for {
		gc.LogInfo("", "", "starting credential renewal timer...")
		<-time.Tick(24 * time.Hour)
		if err != nil {
			panic(err)
		}

		if time.Now().UTC().AddDate(0, 0, 5).Unix() == int64(expTime) {
			gc.LogInfo("", "", "renew credentials...")
		} else if time.Now().UTC().Unix() == int64(expTime) {
			gc.LogInfo("", "", "renew credentials...")
		} else if time.Now().UTC().Unix() > int64(expTime) {
			gc.LogInfo("", "", "renew credentials...")
		}
	}
}
