package sdk

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"errors"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	v1 "go.alargerobot.dev/gatekeeper/sdk/rpc/endpoint_manager/v1"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
)

type GatekeeperClient struct {
	config          GatekeeperClientConfig
	grpcClient      *grpc.ClientConn
	endpointManager v1.EndpointManagerClient
	epsServer       *endpointServicesServer
}

type GatekeeperClientConfig struct {
	GatekeeperAPIAddress string
	EndpointServicesPort int
}

type DeviceAuthRequest struct {
	Message   string
	RequestID string
}

type DeviceAuthClientResponse struct {
	Message   string `json:"message"`
	Signature string `json:"signature"`
	RequestID string `json:"requestID"`
}

// # Description
//
// NewGatekeeperClient initializes the gRPC client reponsible for commuicating with Gatekeeper and
// starts listeners for various Gatekeeper services.
//
// # Usage note
//
// Connection to Gatekeeper currently requires the TLS certificates generated by Gatekeeper upon
// service creation, be present in the same directory as the service binary. The files must share the name
// of the service binary and have the following file extensions:
//
//   - .crt for the certificate itself
//   - .key for the private key.
//
// Also present should be the Gatekeeper root CA certificate in a file named: "gkca.pem"
func NewGatekeeperClient(config GatekeeperClientConfig) *GatekeeperClient {
	cert, err := tls.LoadX509KeyPair(filepath.Base(os.Args[0])+".crt", filepath.Base(os.Args[0])+".key")
	if err != nil {
		panic(err)
	}

	ca := x509.NewCertPool()
	caFile, _ := os.ReadFile("gkca.pem")

	ca.AppendCertsFromPEM(caFile)

	grpcClient, e := grpc.NewClient("dns:///"+config.GatekeeperAPIAddress, grpc.WithTransportCredentials(
		credentials.NewTLS(&tls.Config{
			ServerName:   "gatekeeper",
			Certificates: []tls.Certificate{cert},
			RootCAs:      ca,
		})))

	if e != nil {
		panic(e)
	}

	ess := NewEndpointServiceServer(false, "")
	go ess.ListenAndServe(config.EndpointServicesPort)

	gkc := &GatekeeperClient{
		epsServer:       ess,
		config:          config,
		grpcClient:      grpcClient,
		endpointManager: v1.NewEndpointManagerClient(grpcClient),
	}

	return gkc
}

// # Description
//
// RegisterGRPCServiceEndpoint registers a gRPC service reachable at "address" with Gatekeeper
//   - address should be formated: <ip-address:port>
//   - tags are optional, specify []string{} if no tags are to applied
func (gc *GatekeeperClient) RegisterGRPCServiceEndpoint(serviceName, grpcServiceName, address string, tags []string) error {
	return gc.registerEPInternal(serviceName, grpcServiceName, address, tags)
}

// # Description
//
// RegisterServiceEndpoint registers a non-gRPC service reachable at "address" with Gatekeeper
//   - address should be formated: <ip-address:port>
//   - tags are optional, specify []string{} if no tags are to applied
func (gc *GatekeeperClient) RegisterServiceEndpoint(serviceName, address string, tags []string) error {
	return gc.registerEPInternal(serviceName, serviceName, address, tags)
}

func (gc *GatekeeperClient) registerEPInternal(serviceName, endpointName, address string, tags []string) error {
	addrParts := strings.Split(address, ":")

	if len(addrParts) != 2 {
		return errors.New("invalid address specified. address format is: <ip-address:port>")
	}

	_, e := gc.endpointManager.RegisterServiceEndpoint(context.Background(), &v1.NewServiceEndpoint{
		Tags:             tags,
		Endpoint:         address,
		ServiceName:      serviceName,
		EndpointName:     endpointName,
		HealthCheckRoute: "https://" + addrParts[0] + ":" + strconv.Itoa(gc.config.EndpointServicesPort) + "/ping",
	})
	return e
}
