package sdk

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"errors"
	"os"
	"regexp"
	"runtime"
	"strconv"
	"strings"

	"github.com/sirupsen/logrus"
	cs "go.alargerobot.dev/gatekeeper/sdk/rpc/config/v1"
	ep "go.alargerobot.dev/gatekeeper/sdk/rpc/endpoint_manager/v1"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/protobuf/encoding/protojson"
)

type GatekeeperClient struct {
	config          GatekeeperClientConfig
	grpcClient      *grpc.ClientConn
	configService   cs.ConfigServiceClient
	endpointManager ep.EndpointManagerClient
	epsServer       *endpointServicesServer
	credentials     cs.ServiceCredentials
	logger          *logrus.Logger
}

type GatekeeperClientConfig struct {
	ServiceName                 string
	GatekeeperAPIAddress        string
	EndpointServicesPort        int
	CredentialsRenewedHandler   func()
	ClientIsRunningOnKubernetes bool
}

type DeviceAuthRequest struct {
	Message   string
	RequestID string
}

type DeviceAuthClientResponse struct {
	Message   string `json:"message"`
	Signature string `json:"signature"`
	RequestID string `json:"requestID"`
}

// # Description
//
// NewGatekeeperClient initializes the gRPC client reponsible for commuicating with Gatekeeper and
// starts listeners for various Gatekeeper services.
//
// # Usage note
//
// Connection to Gatekeeper currently requires the certificate blob generated by Gatekeeper upon
// service creation, be present in the same directory as the service binary. These credentials
// should be saved completely unmodified, in a in a JSON file named "gatekeeper-credentials.json"
// in the same folder as the server binary. Optionally you can also provide the path to the file
// in an environment variable named "CREDENTIALS_FILE_PATH"
func NewGatekeeperClient(config GatekeeperClientConfig) *GatekeeperClient {
	var e error
	var credsFilePath string
	var gkCreds cs.ServiceCredentials

	if path, set := os.LookupEnv("CREDENTIALS_FILE_PATH"); set {
		credsFilePath = path
	} else {
		credsFilePath = "gatekeeper-credentials.json"
	}

	creds, e := os.ReadFile(credsFilePath)
	if e != nil {
		panic(e)
	}

	credsStr := string(creds)
	if strings.HasPrefix(credsStr, "base64:") {
		creds, e = base64.StdEncoding.DecodeString(credsStr[7:])
		if e != nil {
			panic(e)
		}
	}

	e = protojson.Unmarshal(creds, &gkCreds)
	if e != nil {
		panic(e)
	}

	cert, err := tls.X509KeyPair([]byte(gkCreds.Certificate), []byte(gkCreds.PrivateKey))
	if err != nil {
		panic(err)
	}

	ca := x509.NewCertPool()
	caFile := []byte(gkCreds.CaCert)

	ca.AppendCertsFromPEM(caFile)

	grpcClient, e := grpc.NewClient("dns:///"+config.GatekeeperAPIAddress, grpc.WithTransportCredentials(
		credentials.NewTLS(&tls.Config{
			RootCAs:      ca,
			ServerName:   "gatekeeper",
			Certificates: []tls.Certificate{cert},
		})))

	if e != nil {
		panic(e)
	}

	gkc := &GatekeeperClient{
		config:          config,
		grpcClient:      grpcClient,
		credentials:     gkCreds,
		configService:   cs.NewConfigServiceClient(grpcClient),
		endpointManager: ep.NewEndpointManagerClient(grpcClient),
	}
	gkc.epsServer = newEndpointServiceServer(false, "", gkc, gkc.newCredsReceievedFromGK)
	go gkc.epsServer.ListenAndServe(config.EndpointServicesPort)

	gkc.logger = logrus.New()
	gkc.logger.Out = os.Stderr
	gkc.logger.SetLevel(logrus.DebugLevel)

	return gkc
}

// # Description
//
// RegisterGRPCServiceEndpoint registers a gRPC service reachable at "address" with Gatekeeper
//   - address should be formated: <ip-address:port>
//   - tags are optional, specify []string{} if no tags are to applied
func (gc *GatekeeperClient) RegisterGRPCServiceEndpoint(serviceName, grpcServiceName, address string, tags []string) error {
	return gc.registerEPInternal(serviceName, grpcServiceName, address, tags)
}

// # Description
//
// RegisterServiceEndpoint registers a non-gRPC service reachable at "address" with Gatekeeper
//   - address should be formated: <ip-address:port>
//   - tags are optional, specify []string{} if no tags are to applied
func (gc *GatekeeperClient) RegisterServiceEndpoint(serviceName, address string, tags []string) error {
	return gc.registerEPInternal(serviceName, serviceName, address, tags)
}

// GetCredentials returns already loaded Gatekeeper credentials.
func (gc *GatekeeperClient) GetCredentials() *cs.ServiceCredentials {
	return &gc.credentials
}

func (gc *GatekeeperClient) registerEPInternal(serviceName, endpointName, address string, tags []string) error {
	addrParts := strings.Split(address, ":")
	if len(addrParts) != 2 {
		return errors.New("invalid address specified. address format is: <ip-address:port>")
	}

	hcrIP := addrParts[0]

	if gc.config.ClientIsRunningOnKubernetes {
		//Ignore the value of address in favor of our own. Minus the port, we can keep the port.

		if actualIP, err := GetLoadBalancerIP(serviceName); err == nil {
			hcrIP = actualIP
			address = actualIP + ":" + addrParts[1]
			gc.logInfo("newAddress", address, "running in a k8s pod, overriding provided outbound IP")
		} else {
			gc.logError("", "", "failed to get external IP, this will cause the service to not be reachable by Gatekeeper")
		}
	}

	_, e := gc.endpointManager.RegisterServiceEndpoint(context.Background(), &ep.NewServiceEndpoint{
		Tags:                      tags,
		Endpoint:                  address,
		ServiceName:               serviceName,
		EndpointName:              endpointName,
		ClientRunningInKubernetes: gc.config.ClientIsRunningOnKubernetes,
		HealthCheckRoute:          "https://" + hcrIP + ":" + strconv.Itoa(gc.config.EndpointServicesPort) + "/ping",
	})
	return e
}
func (gc *GatekeeperClient) logInfo(extraKey string, extraValue interface{}, entry interface{}) {
	pc, _, line, _ := runtime.Caller(1)
	funcObj := runtime.FuncForPC(pc)
	runtimeFunc := regexp.MustCompile(`^.*\.(.*)$`)
	name := runtimeFunc.ReplaceAllString(funcObj.Name(), "$1")

	if extraKey != "" {
		gc.logger.WithFields(logrus.Fields{extraKey: extraValue, "func": name, "line": line, "originator": "gatekeeper-sdk"}).Infoln(entry)
	} else {
		gc.logger.WithFields(logrus.Fields{"func": name, "line": line, "originator": "gatekeeper-sdk"}).Infoln(entry)
	}
}
func (gc *GatekeeperClient) logWarn(extraKey string, extraValue interface{}, entry interface{}) {
	pc, _, line, _ := runtime.Caller(1)
	funcObj := runtime.FuncForPC(pc)
	runtimeFunc := regexp.MustCompile(`^.*\.(.*)$`)
	name := runtimeFunc.ReplaceAllString(funcObj.Name(), "$1")

	if extraKey != "" {
		gc.logger.WithFields(logrus.Fields{extraKey: extraValue, "func": name, "line": line, "originator": "gatekeeper-sdk"}).Warnln(entry)
	} else {
		gc.logger.WithFields(logrus.Fields{"func": name, "line": line, "originator": "gatekeeper-sdk"}).Warnln(entry)
	}
}
func (gc *GatekeeperClient) logError(extraKey string, extraValue interface{}, entry interface{}) {
	pc, _, line, _ := runtime.Caller(1)
	funcObj := runtime.FuncForPC(pc)
	runtimeFunc := regexp.MustCompile(`^.*\.(.*)$`)
	name := runtimeFunc.ReplaceAllString(funcObj.Name(), "$1")

	if extraKey != "" {
		gc.logger.WithFields(logrus.Fields{extraKey: extraValue, "func": name, "line": line, "originator": "gatekeeper-sdk"}).Errorln(entry)
	} else {
		gc.logger.WithFields(logrus.Fields{"func": name, "line": line, "originator": "gatekeeper-sdk"}).Errorln(entry)
	}
}
func (gc *GatekeeperClient) newCredsReceievedFromGK(credentials cs.ServiceCredentials) {
	if gc.config.ClientIsRunningOnKubernetes {
		err := ForceExternalSecretSync(gc.config.ServiceName)
		if err != nil {
			gc.logWarn("action", "ForceExternalSecretSync", err)
		}
	} else {
		newCreds, _ := protojson.Marshal(&credentials)
		e := os.WriteFile("gatekeeper-credentials.json", newCreds, 0o600)
		if e != nil {
			panic(e)
		}
	}
	gc.credentials = credentials
	gc.config.CredentialsRenewedHandler()
}
