// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: ConfigService.proto

package v1

import (
	types "go.alargerobot.dev/gatekeeper/sdk/rpc/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_ConfigService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_ConfigService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_ConfigService_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Alias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Route         string                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alias) Reset() {
	*x = Alias{}
	mi := &file_ConfigService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alias) ProtoMessage() {}

func (x *Alias) ProtoReflect() protoreflect.Message {
	mi := &file_ConfigService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) {
	return file_ConfigService_proto_rawDescGZIP(), []int{1}
}

func (x *Alias) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Alias) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

type Namespace struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Base                   string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Services               []string               `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	DomainSecurityPolicies []string               `protobuf:"bytes,3,rep,name=domainSecurityPolicies,proto3" json:"domainSecurityPolicies,omitempty"`
	GatekeeperManagedCerts bool                   `protobuf:"varint,4,opt,name=gatekeeperManagedCerts,proto3" json:"gatekeeperManagedCerts,omitempty"`
	Id                     string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_ConfigService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_ConfigService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_ConfigService_proto_rawDescGZIP(), []int{2}
}

func (x *Namespace) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Namespace) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Namespace) GetDomainSecurityPolicies() []string {
	if x != nil {
		return x.DomainSecurityPolicies
	}
	return nil
}

func (x *Namespace) GetGatekeeperManagedCerts() bool {
	if x != nil {
		return x.GatekeeperManagedCerts
	}
	return false
}

func (x *Namespace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Service struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Name                      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Internal                  bool                   `protobuf:"varint,2,opt,name=internal,proto3" json:"internal,omitempty"`
	IsFrostService            bool                   `protobuf:"varint,3,opt,name=isFrostService,proto3" json:"isFrostService,omitempty"`
	SecurityPolicies          []string               `protobuf:"bytes,5,rep,name=securityPolicies,proto3" json:"securityPolicies,omitempty"`
	Id                        string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	AllowsExternalDeviceLogin bool                   `protobuf:"varint,7,opt,name=allowsExternalDeviceLogin,proto3" json:"allowsExternalDeviceLogin,omitempty"`
	EnableGRPCGateway         bool                   `protobuf:"varint,8,opt,name=enableGRPCGateway,proto3" json:"enableGRPCGateway,omitempty"`
	RouteAliases              []*Alias               `protobuf:"bytes,9,rep,name=routeAliases,proto3" json:"routeAliases,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_ConfigService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_ConfigService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_ConfigService_proto_rawDescGZIP(), []int{3}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *Service) GetIsFrostService() bool {
	if x != nil {
		return x.IsFrostService
	}
	return false
}

func (x *Service) GetSecurityPolicies() []string {
	if x != nil {
		return x.SecurityPolicies
	}
	return nil
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetAllowsExternalDeviceLogin() bool {
	if x != nil {
		return x.AllowsExternalDeviceLogin
	}
	return false
}

func (x *Service) GetEnableGRPCGateway() bool {
	if x != nil {
		return x.EnableGRPCGateway
	}
	return false
}

func (x *Service) GetRouteAliases() []*Alias {
	if x != nil {
		return x.RouteAliases
	}
	return nil
}

type ServiceCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaCert        string                 `protobuf:"bytes,1,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	Certificate   string                 `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	ExpiresAt     uint64                 `protobuf:"varint,3,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	IssuerCert    string                 `protobuf:"bytes,4,opt,name=issuerCert,proto3" json:"issuerCert,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCredentials) Reset() {
	*x = ServiceCredentials{}
	mi := &file_ConfigService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCredentials) ProtoMessage() {}

func (x *ServiceCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_ConfigService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCredentials.ProtoReflect.Descriptor instead.
func (*ServiceCredentials) Descriptor() ([]byte, []int) {
	return file_ConfigService_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceCredentials) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *ServiceCredentials) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *ServiceCredentials) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ServiceCredentials) GetIssuerCert() string {
	if x != nil {
		return x.IssuerCert
	}
	return ""
}

func (x *ServiceCredentials) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type NewServiceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SvcDetails      *Service               `protobuf:"bytes,1,opt,name=svcDetails,proto3" json:"svcDetails,omitempty"`
	ParentNamespace string                 `protobuf:"bytes,2,opt,name=parentNamespace,proto3" json:"parentNamespace,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NewServiceRequest) Reset() {
	*x = NewServiceRequest{}
	mi := &file_ConfigService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewServiceRequest) ProtoMessage() {}

func (x *NewServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ConfigService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewServiceRequest.ProtoReflect.Descriptor instead.
func (*NewServiceRequest) Descriptor() ([]byte, []int) {
	return file_ConfigService_proto_rawDescGZIP(), []int{5}
}

func (x *NewServiceRequest) GetSvcDetails() *Service {
	if x != nil {
		return x.SvcDetails
	}
	return nil
}

func (x *NewServiceRequest) GetParentNamespace() string {
	if x != nil {
		return x.ParentNamespace
	}
	return ""
}

type NewServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cert          *ServiceCredentials    `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewServiceResponse) Reset() {
	*x = NewServiceResponse{}
	mi := &file_ConfigService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewServiceResponse) ProtoMessage() {}

func (x *NewServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ConfigService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewServiceResponse.ProtoReflect.Descriptor instead.
func (*NewServiceResponse) Descriptor() ([]byte, []int) {
	return file_ConfigService_proto_rawDescGZIP(), []int{6}
}

func (x *NewServiceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewServiceResponse) GetCert() *ServiceCredentials {
	if x != nil {
		return x.Cert
	}
	return nil
}

type NewNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *Namespace             `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewNamespaceRequest) Reset() {
	*x = NewNamespaceRequest{}
	mi := &file_ConfigService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewNamespaceRequest) ProtoMessage() {}

func (x *NewNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ConfigService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewNamespaceRequest.ProtoReflect.Descriptor instead.
func (*NewNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_ConfigService_proto_rawDescGZIP(), []int{7}
}

func (x *NewNamespaceRequest) GetDomain() *Namespace {
	if x != nil {
		return x.Domain
	}
	return nil
}

type ByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByNameRequest) Reset() {
	*x = ByNameRequest{}
	mi := &file_ConfigService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByNameRequest) ProtoMessage() {}

func (x *ByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ConfigService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByNameRequest.ProtoReflect.Descriptor instead.
func (*ByNameRequest) Descriptor() ([]byte, []int) {
	return file_ConfigService_proto_rawDescGZIP(), []int{8}
}

func (x *ByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Route         string                 `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasRequest) Reset() {
	*x = AliasRequest{}
	mi := &file_ConfigService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasRequest) ProtoMessage() {}

func (x *AliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ConfigService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasRequest.ProtoReflect.Descriptor instead.
func (*AliasRequest) Descriptor() ([]byte, []int) {
	return file_ConfigService_proto_rawDescGZIP(), []int{9}
}

func (x *AliasRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AliasRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *AliasRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

var File_ConfigService_proto protoreflect.FileDescriptor

const file_ConfigService_proto_rawDesc = "" +
	"\n" +
	"\x13ConfigService.proto\x12\x14gatekeeper.config.v1\x1a\vtypes.proto\"\x14\n" +
	"\x02ID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x05Alias\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x14\n" +
	"\x05route\x18\x02 \x01(\tR\x05route\"\xbb\x01\n" +
	"\tNamespace\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x1a\n" +
	"\bservices\x18\x02 \x03(\tR\bservices\x126\n" +
	"\x16domainSecurityPolicies\x18\x03 \x03(\tR\x16domainSecurityPolicies\x126\n" +
	"\x16gatekeeperManagedCerts\x18\x04 \x01(\bR\x16gatekeeperManagedCerts\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\"\xca\x02\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\binternal\x18\x02 \x01(\bR\binternal\x12&\n" +
	"\x0eisFrostService\x18\x03 \x01(\bR\x0eisFrostService\x12*\n" +
	"\x10securityPolicies\x18\x05 \x03(\tR\x10securityPolicies\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12<\n" +
	"\x19allowsExternalDeviceLogin\x18\a \x01(\bR\x19allowsExternalDeviceLogin\x12,\n" +
	"\x11enableGRPCGateway\x18\b \x01(\bR\x11enableGRPCGateway\x12?\n" +
	"\frouteAliases\x18\t \x03(\v2\x1b.gatekeeper.config.v1.AliasR\frouteAliases\"\xae\x01\n" +
	"\x12ServiceCredentials\x12\x17\n" +
	"\aca_cert\x18\x01 \x01(\tR\x06caCert\x12 \n" +
	"\vcertificate\x18\x02 \x01(\tR\vcertificate\x12\x1c\n" +
	"\texpiresAt\x18\x03 \x01(\x04R\texpiresAt\x12\x1e\n" +
	"\n" +
	"issuerCert\x18\x04 \x01(\tR\n" +
	"issuerCert\x12\x1f\n" +
	"\vprivate_key\x18\x05 \x01(\tR\n" +
	"privateKey\"|\n" +
	"\x11NewServiceRequest\x12=\n" +
	"\n" +
	"svcDetails\x18\x01 \x01(\v2\x1d.gatekeeper.config.v1.ServiceR\n" +
	"svcDetails\x12(\n" +
	"\x0fparentNamespace\x18\x02 \x01(\tR\x0fparentNamespace\"b\n" +
	"\x12NewServiceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\x04cert\x18\x02 \x01(\v2(.gatekeeper.config.v1.ServiceCredentialsR\x04cert\"N\n" +
	"\x13NewNamespaceRequest\x127\n" +
	"\x06domain\x18\x01 \x01(\v2\x1f.gatekeeper.config.v1.NamespaceR\x06domain\"#\n" +
	"\rByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"J\n" +
	"\fAliasRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x14\n" +
	"\x05route\x18\x03 \x01(\tR\x05route2\xe0\x06\n" +
	"\rConfigService\x12_\n" +
	"\n" +
	"NewService\x12'.gatekeeper.config.v1.NewServiceRequest\x1a(.gatekeeper.config.v1.NewServiceResponse\x12S\n" +
	"\fNewNamespace\x12).gatekeeper.config.v1.NewNamespaceRequest\x1a\x18.gatekeeper.config.v1.ID\x12U\n" +
	"\rNewRouteAlias\x12\".gatekeeper.config.v1.AliasRequest\x1a .gatekeeper.services.types.Empty\x12I\n" +
	"\x0eGetServiceByID\x12\x18.gatekeeper.config.v1.ID\x1a\x1d.gatekeeper.config.v1.Service\x12M\n" +
	"\x10GetNamespaceByID\x12\x18.gatekeeper.config.v1.ID\x1a\x1f.gatekeeper.config.v1.Namespace\x12Z\n" +
	"\x12GetNamespaceByName\x12#.gatekeeper.config.v1.ByNameRequest\x1a\x1f.gatekeeper.config.v1.Namespace\x12V\n" +
	"\x10GetServiceByName\x12#.gatekeeper.config.v1.ByNameRequest\x1a\x1d.gatekeeper.config.v1.Service\x12M\n" +
	"\x0fDeleteNamespace\x12\x18.gatekeeper.config.v1.ID\x1a .gatekeeper.services.types.Empty\x12K\n" +
	"\rDeleteService\x12\x18.gatekeeper.config.v1.ID\x1a .gatekeeper.services.types.Empty\x12X\n" +
	"\x12RequestCertRenewal\x12\x18.gatekeeper.config.v1.ID\x1a(.gatekeeper.config.v1.NewServiceResponseB\fZ\n" +
	"/config/v1b\x06proto3"

var (
	file_ConfigService_proto_rawDescOnce sync.Once
	file_ConfigService_proto_rawDescData []byte
)

func file_ConfigService_proto_rawDescGZIP() []byte {
	file_ConfigService_proto_rawDescOnce.Do(func() {
		file_ConfigService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ConfigService_proto_rawDesc), len(file_ConfigService_proto_rawDesc)))
	})
	return file_ConfigService_proto_rawDescData
}

var file_ConfigService_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ConfigService_proto_goTypes = []any{
	(*ID)(nil),                  // 0: gatekeeper.config.v1.ID
	(*Alias)(nil),               // 1: gatekeeper.config.v1.Alias
	(*Namespace)(nil),           // 2: gatekeeper.config.v1.Namespace
	(*Service)(nil),             // 3: gatekeeper.config.v1.Service
	(*ServiceCredentials)(nil),  // 4: gatekeeper.config.v1.ServiceCredentials
	(*NewServiceRequest)(nil),   // 5: gatekeeper.config.v1.NewServiceRequest
	(*NewServiceResponse)(nil),  // 6: gatekeeper.config.v1.NewServiceResponse
	(*NewNamespaceRequest)(nil), // 7: gatekeeper.config.v1.NewNamespaceRequest
	(*ByNameRequest)(nil),       // 8: gatekeeper.config.v1.ByNameRequest
	(*AliasRequest)(nil),        // 9: gatekeeper.config.v1.AliasRequest
	(*types.Empty)(nil),         // 10: gatekeeper.services.types.Empty
}
var file_ConfigService_proto_depIdxs = []int32{
	1,  // 0: gatekeeper.config.v1.Service.routeAliases:type_name -> gatekeeper.config.v1.Alias
	3,  // 1: gatekeeper.config.v1.NewServiceRequest.svcDetails:type_name -> gatekeeper.config.v1.Service
	4,  // 2: gatekeeper.config.v1.NewServiceResponse.cert:type_name -> gatekeeper.config.v1.ServiceCredentials
	2,  // 3: gatekeeper.config.v1.NewNamespaceRequest.domain:type_name -> gatekeeper.config.v1.Namespace
	5,  // 4: gatekeeper.config.v1.ConfigService.NewService:input_type -> gatekeeper.config.v1.NewServiceRequest
	7,  // 5: gatekeeper.config.v1.ConfigService.NewNamespace:input_type -> gatekeeper.config.v1.NewNamespaceRequest
	9,  // 6: gatekeeper.config.v1.ConfigService.NewRouteAlias:input_type -> gatekeeper.config.v1.AliasRequest
	0,  // 7: gatekeeper.config.v1.ConfigService.GetServiceByID:input_type -> gatekeeper.config.v1.ID
	0,  // 8: gatekeeper.config.v1.ConfigService.GetNamespaceByID:input_type -> gatekeeper.config.v1.ID
	8,  // 9: gatekeeper.config.v1.ConfigService.GetNamespaceByName:input_type -> gatekeeper.config.v1.ByNameRequest
	8,  // 10: gatekeeper.config.v1.ConfigService.GetServiceByName:input_type -> gatekeeper.config.v1.ByNameRequest
	0,  // 11: gatekeeper.config.v1.ConfigService.DeleteNamespace:input_type -> gatekeeper.config.v1.ID
	0,  // 12: gatekeeper.config.v1.ConfigService.DeleteService:input_type -> gatekeeper.config.v1.ID
	0,  // 13: gatekeeper.config.v1.ConfigService.RequestCertRenewal:input_type -> gatekeeper.config.v1.ID
	6,  // 14: gatekeeper.config.v1.ConfigService.NewService:output_type -> gatekeeper.config.v1.NewServiceResponse
	0,  // 15: gatekeeper.config.v1.ConfigService.NewNamespace:output_type -> gatekeeper.config.v1.ID
	10, // 16: gatekeeper.config.v1.ConfigService.NewRouteAlias:output_type -> gatekeeper.services.types.Empty
	3,  // 17: gatekeeper.config.v1.ConfigService.GetServiceByID:output_type -> gatekeeper.config.v1.Service
	2,  // 18: gatekeeper.config.v1.ConfigService.GetNamespaceByID:output_type -> gatekeeper.config.v1.Namespace
	2,  // 19: gatekeeper.config.v1.ConfigService.GetNamespaceByName:output_type -> gatekeeper.config.v1.Namespace
	3,  // 20: gatekeeper.config.v1.ConfigService.GetServiceByName:output_type -> gatekeeper.config.v1.Service
	10, // 21: gatekeeper.config.v1.ConfigService.DeleteNamespace:output_type -> gatekeeper.services.types.Empty
	10, // 22: gatekeeper.config.v1.ConfigService.DeleteService:output_type -> gatekeeper.services.types.Empty
	6,  // 23: gatekeeper.config.v1.ConfigService.RequestCertRenewal:output_type -> gatekeeper.config.v1.NewServiceResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ConfigService_proto_init() }
func file_ConfigService_proto_init() {
	if File_ConfigService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ConfigService_proto_rawDesc), len(file_ConfigService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ConfigService_proto_goTypes,
		DependencyIndexes: file_ConfigService_proto_depIdxs,
		MessageInfos:      file_ConfigService_proto_msgTypes,
	}.Build()
	File_ConfigService_proto = out.File
	file_ConfigService_proto_goTypes = nil
	file_ConfigService_proto_depIdxs = nil
}
