// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: ConfigService.proto

package v1

import (
	context "context"
	types "go.alargerobot.dev/gatekeeper/sdk/rpc/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigService_NewService_FullMethodName         = "/gatekeeper.config.v1.ConfigService/NewService"
	ConfigService_NewNamespace_FullMethodName       = "/gatekeeper.config.v1.ConfigService/NewNamespace"
	ConfigService_NewRouteAlias_FullMethodName      = "/gatekeeper.config.v1.ConfigService/NewRouteAlias"
	ConfigService_GetServiceByID_FullMethodName     = "/gatekeeper.config.v1.ConfigService/GetServiceByID"
	ConfigService_GetNamespaceByID_FullMethodName   = "/gatekeeper.config.v1.ConfigService/GetNamespaceByID"
	ConfigService_GetNamespaceByName_FullMethodName = "/gatekeeper.config.v1.ConfigService/GetNamespaceByName"
	ConfigService_GetServiceByName_FullMethodName   = "/gatekeeper.config.v1.ConfigService/GetServiceByName"
	ConfigService_DeleteNamespace_FullMethodName    = "/gatekeeper.config.v1.ConfigService/DeleteNamespace"
	ConfigService_DeleteService_FullMethodName      = "/gatekeeper.config.v1.ConfigService/DeleteService"
	ConfigService_RequestCertRenewal_FullMethodName = "/gatekeeper.config.v1.ConfigService/RequestCertRenewal"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	NewService(ctx context.Context, in *NewServiceRequest, opts ...grpc.CallOption) (*ServiceCredentials, error)
	NewNamespace(ctx context.Context, in *NewNamespaceRequest, opts ...grpc.CallOption) (*ID, error)
	NewRouteAlias(ctx context.Context, in *AliasRequest, opts ...grpc.CallOption) (*types.Empty, error)
	GetServiceByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Service, error)
	GetNamespaceByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Namespace, error)
	GetNamespaceByName(ctx context.Context, in *ByNameRequest, opts ...grpc.CallOption) (*Namespace, error)
	GetServiceByName(ctx context.Context, in *ByNameRequest, opts ...grpc.CallOption) (*Service, error)
	DeleteNamespace(ctx context.Context, in *ID, opts ...grpc.CallOption) (*types.Empty, error)
	DeleteService(ctx context.Context, in *ID, opts ...grpc.CallOption) (*types.Empty, error)
	RequestCertRenewal(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ServiceCredentials, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) NewService(ctx context.Context, in *NewServiceRequest, opts ...grpc.CallOption) (*ServiceCredentials, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceCredentials)
	err := c.cc.Invoke(ctx, ConfigService_NewService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) NewNamespace(ctx context.Context, in *NewNamespaceRequest, opts ...grpc.CallOption) (*ID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ID)
	err := c.cc.Invoke(ctx, ConfigService_NewNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) NewRouteAlias(ctx context.Context, in *AliasRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, ConfigService_NewRouteAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetServiceByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, ConfigService_GetServiceByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetNamespaceByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Namespace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Namespace)
	err := c.cc.Invoke(ctx, ConfigService_GetNamespaceByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetNamespaceByName(ctx context.Context, in *ByNameRequest, opts ...grpc.CallOption) (*Namespace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Namespace)
	err := c.cc.Invoke(ctx, ConfigService_GetNamespaceByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetServiceByName(ctx context.Context, in *ByNameRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, ConfigService_GetServiceByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeleteNamespace(ctx context.Context, in *ID, opts ...grpc.CallOption) (*types.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, ConfigService_DeleteNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeleteService(ctx context.Context, in *ID, opts ...grpc.CallOption) (*types.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, ConfigService_DeleteService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) RequestCertRenewal(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ServiceCredentials, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceCredentials)
	err := c.cc.Invoke(ctx, ConfigService_RequestCertRenewal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
type ConfigServiceServer interface {
	NewService(context.Context, *NewServiceRequest) (*ServiceCredentials, error)
	NewNamespace(context.Context, *NewNamespaceRequest) (*ID, error)
	NewRouteAlias(context.Context, *AliasRequest) (*types.Empty, error)
	GetServiceByID(context.Context, *ID) (*Service, error)
	GetNamespaceByID(context.Context, *ID) (*Namespace, error)
	GetNamespaceByName(context.Context, *ByNameRequest) (*Namespace, error)
	GetServiceByName(context.Context, *ByNameRequest) (*Service, error)
	DeleteNamespace(context.Context, *ID) (*types.Empty, error)
	DeleteService(context.Context, *ID) (*types.Empty, error)
	RequestCertRenewal(context.Context, *ID) (*ServiceCredentials, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) NewService(context.Context, *NewServiceRequest) (*ServiceCredentials, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewService not implemented")
}
func (UnimplementedConfigServiceServer) NewNamespace(context.Context, *NewNamespaceRequest) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewNamespace not implemented")
}
func (UnimplementedConfigServiceServer) NewRouteAlias(context.Context, *AliasRequest) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewRouteAlias not implemented")
}
func (UnimplementedConfigServiceServer) GetServiceByID(context.Context, *ID) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceByID not implemented")
}
func (UnimplementedConfigServiceServer) GetNamespaceByID(context.Context, *ID) (*Namespace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamespaceByID not implemented")
}
func (UnimplementedConfigServiceServer) GetNamespaceByName(context.Context, *ByNameRequest) (*Namespace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamespaceByName not implemented")
}
func (UnimplementedConfigServiceServer) GetServiceByName(context.Context, *ByNameRequest) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceByName not implemented")
}
func (UnimplementedConfigServiceServer) DeleteNamespace(context.Context, *ID) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}
func (UnimplementedConfigServiceServer) DeleteService(context.Context, *ID) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedConfigServiceServer) RequestCertRenewal(context.Context, *ID) (*ServiceCredentials, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCertRenewal not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_NewService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).NewService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_NewService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).NewService(ctx, req.(*NewServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_NewNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).NewNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_NewNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).NewNamespace(ctx, req.(*NewNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_NewRouteAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).NewRouteAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_NewRouteAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).NewRouteAlias(ctx, req.(*AliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetServiceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetServiceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetServiceByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetServiceByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetNamespaceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetNamespaceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetNamespaceByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetNamespaceByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetNamespaceByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetNamespaceByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetNamespaceByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetNamespaceByName(ctx, req.(*ByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetServiceByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetServiceByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetServiceByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetServiceByName(ctx, req.(*ByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_DeleteNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteNamespace(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_DeleteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteService(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_RequestCertRenewal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).RequestCertRenewal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_RequestCertRenewal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).RequestCertRenewal(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gatekeeper.config.v1.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewService",
			Handler:    _ConfigService_NewService_Handler,
		},
		{
			MethodName: "NewNamespace",
			Handler:    _ConfigService_NewNamespace_Handler,
		},
		{
			MethodName: "NewRouteAlias",
			Handler:    _ConfigService_NewRouteAlias_Handler,
		},
		{
			MethodName: "GetServiceByID",
			Handler:    _ConfigService_GetServiceByID_Handler,
		},
		{
			MethodName: "GetNamespaceByID",
			Handler:    _ConfigService_GetNamespaceByID_Handler,
		},
		{
			MethodName: "GetNamespaceByName",
			Handler:    _ConfigService_GetNamespaceByName_Handler,
		},
		{
			MethodName: "GetServiceByName",
			Handler:    _ConfigService_GetServiceByName_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _ConfigService_DeleteNamespace_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _ConfigService_DeleteService_Handler,
		},
		{
			MethodName: "RequestCertRenewal",
			Handler:    _ConfigService_RequestCertRenewal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ConfigService.proto",
}
