// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: EndpointManager.proto

package v1

import (
	types "go.alargerobot.dev/gatekeeper/sdk/rpc/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewServiceEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the service registering the endpoint
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	// User specified tags that aren't used by Gatekeeper for anything
	Tags []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	// IP address and port of the endpoint
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Useful when a service has multiple endpoints that point to different components of that service.
	// Clients can use this to lookup an endpoint for a specific service component.
	EndpointName string `protobuf:"bytes,4,opt,name=endpointName,proto3" json:"endpointName,omitempty"`
	// The endpoint mnaager will periodically make requests to this route to determine whether service is sill
	// alive. If the service does not respond within a configurable time period its endpoint will be removed
	// from the active list.
	HealthCheckRoute string `protobuf:"bytes,5,opt,name=healthCheckRoute,proto3" json:"healthCheckRoute,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NewServiceEndpoint) Reset() {
	*x = NewServiceEndpoint{}
	mi := &file_EndpointManager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewServiceEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewServiceEndpoint) ProtoMessage() {}

func (x *NewServiceEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_EndpointManager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewServiceEndpoint.ProtoReflect.Descriptor instead.
func (*NewServiceEndpoint) Descriptor() ([]byte, []int) {
	return file_EndpointManager_proto_rawDescGZIP(), []int{0}
}

func (x *NewServiceEndpoint) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *NewServiceEndpoint) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NewServiceEndpoint) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *NewServiceEndpoint) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *NewServiceEndpoint) GetHealthCheckRoute() string {
	if x != nil {
		return x.HealthCheckRoute
	}
	return ""
}

type ServiceEndpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Should be formatted like so: "//<service-name>:<endpoint-name>/<optional;tag;list>"
	Query         string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEndpointRequest) Reset() {
	*x = ServiceEndpointRequest{}
	mi := &file_EndpointManager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEndpointRequest) ProtoMessage() {}

func (x *ServiceEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EndpointManager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEndpointRequest.ProtoReflect.Descriptor instead.
func (*ServiceEndpointRequest) Descriptor() ([]byte, []int) {
	return file_EndpointManager_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceEndpointRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ServiceEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEndpointResponse) Reset() {
	*x = ServiceEndpointResponse{}
	mi := &file_EndpointManager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEndpointResponse) ProtoMessage() {}

func (x *ServiceEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_EndpointManager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEndpointResponse.ProtoReflect.Descriptor instead.
func (*ServiceEndpointResponse) Descriptor() ([]byte, []int) {
	return file_EndpointManager_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceEndpointResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

var File_EndpointManager_proto protoreflect.FileDescriptor

const file_EndpointManager_proto_rawDesc = "" +
	"\n" +
	"\x15EndpointManager.proto\x12\x1egatekeeper.endpoint_manager.v1\x1a\vtypes.proto\"\xb6\x01\n" +
	"\x12NewServiceEndpoint\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\"\n" +
	"\fendpointName\x18\x04 \x01(\tR\fendpointName\x12*\n" +
	"\x10healthCheckRoute\x18\x05 \x01(\tR\x10healthCheckRoute\".\n" +
	"\x16ServiceEndpointRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"5\n" +
	"\x17ServiceEndpointResponse\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint2\x8a\x02\n" +
	"\x0fEndpointManager\x12\x85\x01\n" +
	"\x12GetServiceEndpoint\x126.gatekeeper.endpoint_manager.v1.ServiceEndpointRequest\x1a7.gatekeeper.endpoint_manager.v1.ServiceEndpointResponse\x12o\n" +
	"\x17RegisterServiceEndpoint\x122.gatekeeper.endpoint_manager.v1.NewServiceEndpoint\x1a .gatekeeper.services.types.EmptyB\x16Z\x14/endpoint_manager/v1b\x06proto3"

var (
	file_EndpointManager_proto_rawDescOnce sync.Once
	file_EndpointManager_proto_rawDescData []byte
)

func file_EndpointManager_proto_rawDescGZIP() []byte {
	file_EndpointManager_proto_rawDescOnce.Do(func() {
		file_EndpointManager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EndpointManager_proto_rawDesc), len(file_EndpointManager_proto_rawDesc)))
	})
	return file_EndpointManager_proto_rawDescData
}

var file_EndpointManager_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_EndpointManager_proto_goTypes = []any{
	(*NewServiceEndpoint)(nil),      // 0: gatekeeper.endpoint_manager.v1.NewServiceEndpoint
	(*ServiceEndpointRequest)(nil),  // 1: gatekeeper.endpoint_manager.v1.ServiceEndpointRequest
	(*ServiceEndpointResponse)(nil), // 2: gatekeeper.endpoint_manager.v1.ServiceEndpointResponse
	(*types.Empty)(nil),             // 3: gatekeeper.services.types.Empty
}
var file_EndpointManager_proto_depIdxs = []int32{
	1, // 0: gatekeeper.endpoint_manager.v1.EndpointManager.GetServiceEndpoint:input_type -> gatekeeper.endpoint_manager.v1.ServiceEndpointRequest
	0, // 1: gatekeeper.endpoint_manager.v1.EndpointManager.RegisterServiceEndpoint:input_type -> gatekeeper.endpoint_manager.v1.NewServiceEndpoint
	2, // 2: gatekeeper.endpoint_manager.v1.EndpointManager.GetServiceEndpoint:output_type -> gatekeeper.endpoint_manager.v1.ServiceEndpointResponse
	3, // 3: gatekeeper.endpoint_manager.v1.EndpointManager.RegisterServiceEndpoint:output_type -> gatekeeper.services.types.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EndpointManager_proto_init() }
func file_EndpointManager_proto_init() {
	if File_EndpointManager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EndpointManager_proto_rawDesc), len(file_EndpointManager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_EndpointManager_proto_goTypes,
		DependencyIndexes: file_EndpointManager_proto_depIdxs,
		MessageInfos:      file_EndpointManager_proto_msgTypes,
	}.Build()
	File_EndpointManager_proto = out.File
	file_EndpointManager_proto_goTypes = nil
	file_EndpointManager_proto_depIdxs = nil
}
