// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: EndpointManager.proto

package v1

import (
	context "context"
	types "go.alargerobot.dev/gatekeeper/sdk/rpc/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EndpointManager_GetServiceEndpoint_FullMethodName      = "/gatekeeper.endpoint_manager.v1.EndpointManager/GetServiceEndpoint"
	EndpointManager_RegisterServiceEndpoint_FullMethodName = "/gatekeeper.endpoint_manager.v1.EndpointManager/RegisterServiceEndpoint"
)

// EndpointManagerClient is the client API for EndpointManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointManagerClient interface {
	GetServiceEndpoint(ctx context.Context, in *ServiceEndpointRequest, opts ...grpc.CallOption) (*ServiceEndpointResponse, error)
	RegisterServiceEndpoint(ctx context.Context, in *NewServiceEndpoint, opts ...grpc.CallOption) (*types.Empty, error)
}

type endpointManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointManagerClient(cc grpc.ClientConnInterface) EndpointManagerClient {
	return &endpointManagerClient{cc}
}

func (c *endpointManagerClient) GetServiceEndpoint(ctx context.Context, in *ServiceEndpointRequest, opts ...grpc.CallOption) (*ServiceEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceEndpointResponse)
	err := c.cc.Invoke(ctx, EndpointManager_GetServiceEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointManagerClient) RegisterServiceEndpoint(ctx context.Context, in *NewServiceEndpoint, opts ...grpc.CallOption) (*types.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, EndpointManager_RegisterServiceEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndpointManagerServer is the server API for EndpointManager service.
// All implementations must embed UnimplementedEndpointManagerServer
// for forward compatibility.
type EndpointManagerServer interface {
	GetServiceEndpoint(context.Context, *ServiceEndpointRequest) (*ServiceEndpointResponse, error)
	RegisterServiceEndpoint(context.Context, *NewServiceEndpoint) (*types.Empty, error)
	mustEmbedUnimplementedEndpointManagerServer()
}

// UnimplementedEndpointManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEndpointManagerServer struct{}

func (UnimplementedEndpointManagerServer) GetServiceEndpoint(context.Context, *ServiceEndpointRequest) (*ServiceEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceEndpoint not implemented")
}
func (UnimplementedEndpointManagerServer) RegisterServiceEndpoint(context.Context, *NewServiceEndpoint) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterServiceEndpoint not implemented")
}
func (UnimplementedEndpointManagerServer) mustEmbedUnimplementedEndpointManagerServer() {}
func (UnimplementedEndpointManagerServer) testEmbeddedByValue()                         {}

// UnsafeEndpointManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointManagerServer will
// result in compilation errors.
type UnsafeEndpointManagerServer interface {
	mustEmbedUnimplementedEndpointManagerServer()
}

func RegisterEndpointManagerServer(s grpc.ServiceRegistrar, srv EndpointManagerServer) {
	// If the following call pancis, it indicates UnimplementedEndpointManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EndpointManager_ServiceDesc, srv)
}

func _EndpointManager_GetServiceEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointManagerServer).GetServiceEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointManager_GetServiceEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointManagerServer).GetServiceEndpoint(ctx, req.(*ServiceEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointManager_RegisterServiceEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewServiceEndpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointManagerServer).RegisterServiceEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointManager_RegisterServiceEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointManagerServer).RegisterServiceEndpoint(ctx, req.(*NewServiceEndpoint))
	}
	return interceptor(ctx, in, info, handler)
}

// EndpointManager_ServiceDesc is the grpc.ServiceDesc for EndpointManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndpointManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gatekeeper.endpoint_manager.v1.EndpointManager",
	HandlerType: (*EndpointManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceEndpoint",
			Handler:    _EndpointManager_GetServiceEndpoint_Handler,
		},
		{
			MethodName: "RegisterServiceEndpoint",
			Handler:    _EndpointManager_RegisterServiceEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "EndpointManager.proto",
}
